// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvsnIH5Kg2rxasLtmwP6SHw1TycGBND7I',
    appId: '1:108493690664:web:04346f37ae04d9ca05a21d',
    messagingSenderId: '108493690664',
    projectId: 'm-eng-c78cf',
    authDomain: 'm-eng-c78cf.firebaseapp.com',
    storageBucket: 'm-eng-c78cf.appspot.com',
    measurementId: 'G-5447XT6T86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCan0NEPfYDImv_F27qoAgwo7XReteZ1n8',
    appId: '1:108493690664:android:a0957569764c36e305a21d',
    messagingSenderId: '108493690664',
    projectId: 'm-eng-c78cf',
    storageBucket: 'm-eng-c78cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7LDLt8aPvMQxD0_FnhD1wS3zNn5hJtI',
    appId: '1:108493690664:ios:3c97a5f87371fe0605a21d',
    messagingSenderId: '108493690664',
    projectId: 'm-eng-c78cf',
    storageBucket: 'm-eng-c78cf.appspot.com',
    iosClientId: '108493690664-3f6ei6gsaf5id3fa3nav6t1c8eh9aooa.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationEng',
  );
}
